"""empty message

Revision ID: 44343794bdbe
Revises: 
Create Date: 2018-11-29 20:24:05.548556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44343794bdbe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nfc_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('nfc_id')
    )
    op.create_table('catch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('catched_at', sa.DateTime(), nullable=True),
    sa.Column('currently_held', sa.Boolean(), nullable=True),
    sa.Column('timer_started_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catch')
    op.drop_table('team')
    # ### end Alembic commands ###
